---
title: "practice"
author: "kotsubotakuto"
date: "2017年5月8日"
output: 
 html_document:
    toc: true
    toc_depth: 3
---
#ベイジアンネットワークによる株価の上下予測

##パッケージ読み込み

```{r pressure, eval=FALSE}
install.packages("quantmod")
install.packages("deal")
install.packages("data.table")
install.packages("dplyr")
```

```{r setup, include=FALSE}
library(quantmod)
library(deal)
library(dplyr)
library(data.table)
library(foreach)
```

## データの読み込み

```{r}
#訓練データ
TPX_ln <- getSymbols("TPX", src="yahoo", from=as.Date("2015-1-1"), to=as.Date("2015-12-31"), auto.assign=FALSE) #TOPIX
HSI_ln <- getSymbols("HSI", src="yahoo", from=as.Date("2015-1-1"), to=as.Date("2015-12-31"), auto.assign=FALSE) #HSI
INDU_ln <- getSymbols("INDU", src="yahoo", from=as.Date("2015-1-1"), to=as.Date("2015-12-31"), auto.assign=FALSE) #NYダウ
CCMP_ln <- getSymbols("CCMP", src="yahoo", from=as.Date("2015-1-1"), to=as.Date("2015-12-31"), auto.assign=FALSE) #ナスダック
DAX_ln <- getSymbols("DAX", src="yahoo", from=as.Date("2015-1-1"), to=as.Date("2015-12-31"), auto.assign=FALSE) #ドイツ
CAC_ln <- getSymbols("CAC", src="yahoo", from=as.Date("2015-1-1"), to=as.Date("2015-12-31"), auto.assign=FALSE) #フランス

#テストデータ
#TPX_test <- getSymbols("TPX",src="yahoo",from=as.Date("2016-1-1"),to=as.Date("2016-12-31"),auto.assign=FALSE)
```


## データ整理

```{r}
#データを差分化,table変換,終値抽出
ht <- diff(TPX_ln) %>% data.table() %>% dplyr::select(TPX.Close)
#0,1表記,1つ目のデータを削除
TPX_ln <- ifelse(ht > 0, 1, -1)[-1]
length(TPX_ln)#パラメータ数

ht <- diff(HSI_ln) %>% data.table() %>%  dplyr::select(HSI.Close)
HSI_ln <- ifelse(ht > 0, 1, -1)[-1]
length(HSI_ln)

ht <- diff(INDU_ln) %>% data.table() %>%  dplyr::select(INDU.Close)
INDU_ln <- ifelse(ht > 0, 1, -1)[-1]
length(INDU_ln)

ht <- diff(CCMP_ln) %>% data.table() %>%  dplyr::select(CCMP.Close)
CCMP_ln <- ifelse(ht > 0, 1, -1)[-1]
length(CCMP_ln)

ht <- diff(DAX_ln) %>% data.table() %>%  dplyr::select(DAX.Close)
DAX_ln <- ifelse(ht > 0, 1, -1)[-1]
length(DAX_ln)

ht <- diff(CAC_ln) %>% data.table() %>%  dplyr::select(CAC.Close)
CAC_ln <- ifelse(ht > 0, 1, -1)[-1]
length(CAC_ln)

#行列表記
#日数が違うもの削除
kabu <- cbind(TPX_ln, CCMP_ln, CAC_ln,DAX_ln) %>% data.table()
```

## ブラックボックス????

```{r}
kabu[] <- lapply(kabu, as.factor)
kabu.nw <- network(kabu)
plot(kabu.nw)

# 事前分布
kabu.prior <- jointprior(kabu.nw)

# 事後分布
update <- learn(kabu.nw, kabu, kabu.prior)

# ネットワークスコアが最適になるネットワークを探索
post.network <- autosearch(getnetwork(update), kabu, kabu.prior, trace=FALSE)

#プロット
plot(getnetwork(post.network))
#???
localprob(getnetwork(post.network))
```

## ダウ平均

```{r,eval=FALSE}
#XOM読み込めない
getSymbols(c("AAPL","MSFT","PFE","INTC","VZ","GE","CSCO","NKE","IBM","JPM","MRK","V","KO","DIS","WMT","DD","CVX","PG","JNJ"             ,"CAT","AXP","BA","HD","MCD","UTX","GS","UNH","MMM","TRV")             ,from=as.Date("2015-01-01"), to=as.Date("2015-12-31"))
```

```{r,eval=FALSE}
asset <-cbind(AAPL$AAPL.Close,MSFT$MSFT.Close,PFE$PFE.Close,INTC$INTC.Close,VZ$VZ.Close,GE$GE.Close,CSCO$CSCO.Close,NKE$NKE.Close,IBM$IBM.Close,JPM$JPM.Close,MRK$MRK.Close,V$V.Close,KO$KO.Close,DIS$DIS.Close,WMT$WMT.Close,DD$DD.Close,CVX$CVX.Close,PG$PG.Close,JNJ$JNJ.Close,CAT$CAT.Close,AXP$AXP.Close,BA$BA.Close,HD$HD.Close,MCD$MSD.Close,UTX$UTX.Close,GS$GS.Close,UNH$UNH.Close,MMM$MMM.Close,TRV$TRV.Close) 
ht <- diff(asset) %>% data.table()
asset <- ifelse(ht> 0, 1, 0)[-1,] %>% data.table()
```

```{r,eval=FALSE}
asset[] <- lapply(asset, as.factor)
DOW.nw <- network(asset)
plot(DOW.nw)

# 事前分布
DOW.prior <- jointprior(DOW.nw)

# 事後分布
update <- learn(DOW.nw, asset, DOw.prior)

# ネットワークスコアが最適になるネットワークを探索
post.network <- autosearch(getnetwork(update), asset, DOW.prior, trace=FALSE)

#プロット
plot(getnetwork(post.network))
#???
localprob(getnetwork(post.network))
```

