---
title: "gganime"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#devtools::install_github("thomasp85/gganimate")
library(gapminder)
library(ggplot2)
library(gganimate)
library(TDA)
library(dplyr)
```

# sample 1

```{r}
p <- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
 geom_point(alpha = 0.7) +
 scale_colour_manual(values = country_colors) +
 scale_size(range = c(2, 12)) +
 scale_x_log10() +
 facet_wrap(~continent) +
 theme(legend.position = 'none') +
 labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
 transition_time(year) +
 ease_aes('linear')
```

```{r}
animate(p, 100, 10)
```

# sample2

```{r}
library(ggplot2)
library(gganimate)
library(ggforce)
library(tweenr)
#devtools::install_github("tidyverse/ggplot2")
#devtools::install_github("thomasp85/tweenr")
```

```{r}
# Making up data
d <- data.frame(x = rnorm(20), y = rnorm(20), time = sample(100, 20), alpha = 0, 
                size = 1, ease = 'elastic-out', id = 1:20, 
                stringsAsFactors = FALSE)
d2 <- d
d2$time <- d$time + 10
d2$alpha <- 1
d2$size <- 3
d2$ease <- 'linear'
d3 <- d2
d3$time <- d2$time + sample(50:100, 20)
d3$size = 10
d3$ease <- 'bounce-out'
d4 <- d3
d4$y <- min(d$y) - 0.5
d4$size <- 2
d4$time <- d3$time + 10
d5 <- d4
d5$time <- max(d5$time)
df <- rbind(d, d2, d3, d4, d5)

######### Using tweenr ############
dt <- tween_elements(df, 'time', 'id', 'ease', nframes = 500)

######### Not use frame ########
p <- ggplot(data = dt,aes(x=x,y=y, size=size,alpha=alpha)) +
  geom_point() + 
  scale_size(range = c(0.1, 20), guide = 'none') + 
  scale_alpha(range = c(0, 1), guide = 'none') + 
  transition_time(time) +
  ease_aes('linear')
animate(p,100,10)  
  
######### use frame command ########
# error
p <- ggplot(data = dt) + 
    geom_point(aes(x=x, y=y, size=size, alpha=alpha, geom_polygon = .frame)) + 
    scale_size(range = c(0.1, 20), guide = 'none') + 
    scale_alpha(range = c(0, 1), guide = 'none') + 
    ggforce::theme_no_axes()
animation::ani.options(interval = 1/24)
animate(p, 'dropping balls.gif', title_frame = F)
```


# TDA

```{r}
d <- iris
mat <- as.matrix(d[,1:2])
mat_scaled  <- apply(mat,2,scale) %>% as.data.frame()
```

```{r}
mat_scaled %>% 
  ggplot(aes(x=Sepal.Length, y=Sepal.Width)) +
  geom_point(size=50,shape = 21,alpha=0.3,colour="grey",fill="skyblue") +
  geom_point()
```

```{r}
test <- c()
for (i in 1:2) {
  tmp <- mat_scaled %>% mutate(pop = i)
  test <- rbind(test,tmp)
}
```

```{r}
ggplot(test, aes(x=Sepal.Length, y=Sepal.Width,size=pop)) +
  geom_point(shape = 21,alpha=0.3,colour="black",fill="skyblue") +
  geom_point(size = 1) +
  scale_size_continuous(range = c(1, 30)) +
  guides(size=FALSE)
```

```{r}
p <- 
  ggplot(test, aes(x=Sepal.Length, y=Sepal.Width,size=pop)) +
  geom_point(shape = 21,alpha=0.3,colour="black",fill="skyblue") +
  geom_point(size = 1) +
  scale_size_continuous(range = c(1, 30)) +
  guides(size=FALSE) +
  transition_time(pop) +
  ease_aes('linear')
```

```{r}
gganimate::animate(p,100,10)
```


