---
title: "tidyr package"
author: "takuto kotsubo"
date: "2017年6月4日"
output: html_document
---

[tydir for blog](http://uribo.hatenablog.com/entry/2015/12/01/055000)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(ggplot2)
library(broom)
library(dplyr)
library(readr)
library(pipeR)
library(magrittr)
```

```{r}
df_uryu <- readr::read_delim("csv/sample_data.csv",
                             delim = ",",
                             na     = "na",
                             col_types = list(
                              spc_japan = col_character() 
                             ),
                             skip   = 86)
```

```{r}
names(df_uryu)
```

```{r}
# %<>% pipeして戻す
df_uryu %<>% dplyr::select(-ends_with("cord"), -contains("s_date"),
                           -starts_with("stem"), -starts_with("indv_no"),
                           -tag_no05, -tag_no09) 
```

```{r}
glimpse(df_uryu)
```

```{r}
# 文字列変換
# ほかの列にも同時にできない？？？
df_uryu[,2] <- data.frame(lapply(df_uryu[,2], iconv)) 
```

