---
title: "tidyr package"
author: "takuto kotsubo"
date: "2017年6月4日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyr)
library(dplyr)
library(DT)
library(ggplot2)
library(summarytools)
library(gapminder)
```

```{r view}
dfSummary(gapminder) %>% 
  view(method = "render")
```

```{r}
ggplot(gapminder) +
  geom_line(aes(year,lifeExp,group = country))
```

## nest

- 複数要素をまとめる

```{r}
by_country <- gapminder %>% 
  group_by(continent,country) %>% 
  nest()
by_country
```

```{r}
by_country$data[[1]]
```

## map 

- List に対して, 処理

```{r}
by_country <- by_country %>% 
  mutate(model = purrr::map(data, ~ lm(lifeExp ~ year,data = .)))
by_country
```

## unnest

- nest 解除

```{r}
by_country %>% unnest(data)
```

## broom

```{r}
library(broom)
# extract model and fit summaries
by_country %>% unnest(model %>% purrr::map(broom::glance)) 
# extract coefficients
by_country %>% unnest(model %>% purrr::map(broom::tidy))
# extract residuals etc
by_country %>% unnest(model %>% purrr::map(broom::augment))
```

# complete

- 欠損データを補完
- 非指定カラムはNA

```{r}
resources <- frame_data(
  ~year, ~metric, ~value,
  1999, "coal", 100,
  2001, "coal", 50,
  2001, "steel", 200
)
resources
```

```{r}
# 全パターンを表示
resources %>% 
  complete(year,metric)
# 補完方法を指定
resources %>% 
  complete(year = full_seq(year, 1L), metric)
# 複数を一つとして考える
resources %>% 
  complete(nesting(year,metric))
```


